services:
  sql2:
    build: .
    ports:
      - "1433:1433"
    # image: mcr.microsoft.com/mssql/server:2022-latest
    # hostname: 'sql2'
    # environment:
    #   ACCEPT_EULA: 'Y'
    #   MSSQL_SA_PASSWORD: 'Pwd123456@!'
    # ports:
    #   - '1433:1433'
    # command: /opt/mssql-tools/bin/sqlcmd
    # volumes:
    #   - sqlserver-data:/var/opt/mssql

  frontend:
    build: ./UI      
    ports:
      - "3000:3000"      

  backend:
    build: ./Backend/cs6440Backend
    ports:
      - "8000:8000"

